# Generated by Django 2.1.7 on 2019-06-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to='sliders')),
                ('title', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
